version: "2.0"
services:
  php:
    build: './php/'
    networks:
      - backend
    volumes:
      - \Users\sppm0070\Documents\GitHub\M300-Services\LB2\src /var/www/html/
  apache:
    build: './apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - \Users\sppm0070\Documents\GitHub\M300-Services\LB2\src /var/www/html/
  mysql:
    image: mysql:5.6.40
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
networks:
  frontend:
  backend:
